### PR TITLE
Added image comment

### LINKED ISSUE #9: webbj62 checklist
During class I'm going to:  
- [x] Create an issue
- [x] Create a branch
- [x] Make changes to our file
- [x] Make commits
- [x] Make a pull request 
- [x] Perform a peer review
- [x] Merge

### PR DESCRIPTION
**Pull request by webbj62**
These changes are based on and closes #9

### CODE REVIEW

**Review by dorinalora — COMMENTED** [review]
Can you add a spark in the charge?

**Review by dorinalora — COMMENTED** [review]
Overall, very cool :+1:

**Review by dorinalora — CHANGES_REQUESTED** [review]
Please add an emoji to your caption

**Comment by webbj62** [comment]
@dorinalora - Made the recommend change - please review

**Review by dorinalora — APPROVED** [review]

**Comment by dorinalora** [comment]
Great job :100:

**Pull request merged**
